### ISSUE TITLE
Unable to execute RDscan..

### ISSUE THREAD

**Issue by anbazhagan6** [dbespiatykh/RDscan#1]
Looking for: ['snakemake', 'snakedeploy', 'biopython']

Encountered problems while solving:
  - package snakedeploy-0.1.1-pyhdfd78af_1 requires python >=3.8, but none of the providers can be installed

How to execute properly without any error?

**Comment by dbespiatykh** [comment]
I couldn't replicate this issue.

You can try to install the environment this way and see if it works: 

```bash
mamba create -n RDscan -c conda-forge -c bioconda snakemake biopython
```
