### ISSUE TITLE
Error in rule compute_coverage:

### ISSUE THREAD

**Issue by anbazhagan6** [dbespiatykh/RDscan#2]
Error in rule compute_coverage:
    jobid: 16
    output: bed/ERR386816.bed
    conda-env: /mnt/e/Karthisir_mtb/mtb/RDscan/.snakemake/conda/f1da7f6336cc754e535647fdb7c37a30
    shell:

        parallel bedtools genomecov -bga -ibam ::: mapped/ERR386816.bam         | awk '$4<'$(samtools depth  -aa mapped/ERR386816.bam |  awk '{sum+=$3} END {print sum/4411532*0.1}')''            | bedtools merge -d 1500 | bedtools subtract -f 0.30 -a stdin -b config/IS6110.bed -A > bed/ERR386816.bed

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by dbespiatykh** [comment]
I've made some changes, so you can download the latest [version](https://github.com/dbespiatykh/RDscan/releases/tag/v1.0.3r) and try it again. Everything should work now!
