### ISSUE TITLE
Input when running RDscan

### ISSUE THREAD

**Issue by stuber** [dbespiatykh/RDscan#3]
What is the exact input to provide to the command below when trying to determine the RD regions of a sample?  Is the working directory to contain the files to be analyzed?  Please provide examples if possible.  Thanks,

`snakemake --conda-frontend mamba --use-conda -j {Number of cores}`

**Comment by dbespiatykh** [comment]
You should configure workflow as described here: https://github.com/dbespiatykh/RDscan/tree/master/config.
In short, you need to add your samples to `RDscan/config/samples.tsv` like so:

| Run_accession | R1                             | R2                             |
| ------------- | ------------------------------ | ------------------------------ |
| your_sample_A    | /path/to/your_sample_A_1.fastq.gz | /path/to/your_sample_A_2.fastq.gz |
| your_sample_B    | /path/to/your_sample_B_2.fastq.gz | /path/to/your_sample_B_2.fastq.gz |

Then you need to run the *command* you mentioned (inside _RDscan_ directory).
Alternatively, you can use this command (to omit ```mamba```): ```snakemake --cores all --use-conda```.

**Comment by stuber** [comment]
Thanks!

From: Dmitry Bespiatykh ***@***.***>
Date: Tuesday, May 2, 2023 at 2:44 PM
To: dbespiatykh/RDscan ***@***.***>
Cc: Stuber, Tod - MRP-APHIS ***@***.***>, Author ***@***.***>
Subject: Re: [dbespiatykh/RDscan] Input when running RDscan (Issue #3)

You should configure workflow as described here: https://github.com/dbespiatykh/RDscan/tree/master/config.
In short, you need to add your samples to RDscan/config/samples.tsv like so:
Run_accession
R1
R2
your_sample_A
/path/to/your_sample_A_1.fastq.gz
/path/to/your_sample_A_2.fastq.gz
your_sample_B
/path/to/your_sample_B_2.fastq.gz
/path/to/your_sample_B_2.fastq.gz

Then you need to run the command you mentioned (inside RDscan directory).
Alternatively, you can use this command (to omit mamba): snakemake --cores all --use-conda.
