### ISSUE TITLE
AmbiguousRuleException: Rules calculate_proportion and compute_coverage are ambiguous for the file results/bed/28  /test/reads/28_1.fastq.gz.proportion.bed.

### ISSUE THREAD

**Issue by thomasprasad** [dbespiatykh/RDscan#4]
RDscan end with this error with our data, and dry run give probably the results

**Dry run**
/mnt/f/RD/RDscan/workflow/rules/novel_discovery.smk:52: SyntaxWarning: invalid escape sequence '\w'
  input:
Building DAG of jobs...
Nothing to be done (all requested files are present and up to date).

**Our data**

AmbiguousRuleException:
Rules calculate_proportion and compute_coverage are ambiguous for the file results/bed/28  /test/reads/28_1.fastq.gz.proportion.bed.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        calculate_proportion: sample=28  /test/reads/28_1.fastq.gz
        compute_coverage: sample=28  /test/reads/28_1.fastq.gz.proportion
Expected input files:
        calculate_proportion: results/mosdepth_bed/28  /test/reads/28_1.fastq.gz.regions.bed.gz
        compute_coverage: results/mapped/28  /test/reads/28_1.fastq.gz.proportion.bam resources/IS6110.bed
Expected output files:
        calculate_proportion: results/bed/28  /test/reads/28_1.fastq.gz.proportion.bed
        compute_coverage: results/bed/28  /test/reads/28_1.fastq.gz.proportion.bed

**Comment by dbespiatykh** [comment]
Can you provide your samples sheet?

**Comment by thomasprasad** [comment]
Dear Dmitry Bespiatykh,

Please find attached the sample sheet

Regards

Dr. Prasad Thomas
Scientist
In-charge National Salmonella Center (Veterinary) and Anaerobe Laboratory
Division of Bacteriology and Mycology
ICAR-Indian Veterinary Research Institute
Izatnagar, Bareilly- 243122
India
Telephone (O)  +91 0581/2312497
                  (M) +91  6396172186

**Comment by dbespiatykh** [comment]
I do not see any attached files. Can you add it via `Attach files` directly in this GitHub issue thread?

**Comment by thomasprasad** [comment]
please find the attached, I missed

Run_accession	R1	R2
28  /test/reads/28_1.fastq.gz	/test/reads/28_2.fastq.gz

[samples.txt](https://github.com/dbespiatykh/RDscan/files/14219974/samples.txt)

**Comment by dbespiatykh** [comment]
In the provided file, in the second line, you have two spaces instead of a tab character between `28` and `/test/reads/28_1.fastq.gz`. Also make sure that the provided path for files exist, in the current state it leads to the root directory, maybe you want to add `.` before `/` if files located in the `RDscan/test/reads` directory. I have attached the
[samples.txt](https://github.com/dbespiatykh/RDscan/files/14220231/samples.txt) file which works on my computer; in my case, files are located in the `RDscan/test/reads`.

**Comment by thomasprasad** [comment]
Thanks for the suggestion went further, but again ended up in another error with my files
The error doesnt happen with **test fastq files**
localrule compute_coverage:
    input: results/mapped/28.proportion.bam, resources/IS6110.bed
    output: results/bed/28.proportion.bed
    log: logs/bedtools/28.proportion.coverage.log
    jobid: 1
    reason: Missing output files: results/bed/28.proportion.bed
    wildcards: sample=28.proportion
    resources: tmpdir=/tmp

Waiting at most 5 seconds for missing files.
regards

**Comment by dbespiatykh** [comment]
If you send me your `FASTQ` files, I can look further into it.
Also, please attach all log files from `logs/`

**Comment by thomasprasad** [comment]
Dear Dmitry Bespiatykh,

I hope you can access the files through the email, through Github, the file
size was an issue

regards
 28_1.fastq.gz
<https://drive.google.com/file/d/1JP2jFlo1T-phHGFcN3zPiSSGu15XtwXd/view?usp=drive_web>
 28_2.fastq.gz
<https://drive.google.com/file/d/1DY27buU9emHeby70KrDhSjuYiqwHRwop/view?usp=drive_web>
Dr. Prasad Thomas
Scientist
In-charge National Salmonella Center (Veterinary) and Anaerobe Laboratory
Division of Bacteriology and Mycology
ICAR-Indian Veterinary Research Institute
Izatnagar, Bareilly- 243122
India
Telephone (O)  +91 0581/2312497
                  (M) +91  6396172186

**Comment by dbespiatykh** [comment]
I ran `RDscan` using your reads and couldn't reproduce your error, everything worked correctly on Linux and macOS. I did make minor changes to the pipeline to fix `SyntaxWarning`, so you can try to use the latest [version](https://github.com/dbespiatykh/RDscan/releases/tag/v1.0.4).
I also attached the result files for your reads:
[RD_known.xlsx](https://github.com/dbespiatykh/RDscan/files/14222495/RD_known.xlsx) 
[RD_known.bin.txt](https://github.com/dbespiatykh/RDscan/files/14222501/RD_known.bin.txt)
[RD_known.txt](https://github.com/dbespiatykh/RDscan/files/14222502/RD_known.txt)
[RD_putative.txt](https://github.com/dbespiatykh/RDscan/files/14222503/RD_putative.txt)

If the new version still throws an error, send me all log files

**Comment by thomasprasad** [comment]
Hi, still a different kind of issue, 
Same results also in dry run

tried also with also an new to RDscan2 in enviroment.yml file

Log file attatched
[2024-02-10T130809.240069.snakemake.log](https://github.com/dbespiatykh/RDscan/files/14228532/2024-02-10T130809.240069.snakemake.log)

Building DAG of jobs...
WorkflowError:
InputFunctionException (rule bwa_mem, line 2, /mnt/f/RD/RDscan-1.0.4/workflow/rules/mapping.smk):
    Error:
      KeyError: '28.proportion'
    Wildcards:
      sample=28.proportion
    Traceback:
      File "/mnt/f/RD/RDscan-1.0.4/workflow/rules/common.smk", line 19, in get_fastq
      File "/mnt/e/Miniconda3/envs/RDscan2/lib/python3.12/site-packages/pandas/core/indexing.py", line 1192, in __getitem__
      File "/mnt/e/Miniconda3/envs/RDscan2/lib/python3.12/site-packages/pandas/core/indexing.py", line 1432, in _getitem_axis
      File "/mnt/e/Miniconda3/envs/RDscan2/lib/python3.12/site-packages/pandas/core/indexing.py", line 1382, in _get_label
      File "/mnt/e/Miniconda3/envs/RDscan2/lib/python3.12/site-packages/pandas/core/generic.py", line 4295, in xs
      File "/mnt/e/Miniconda3/envs/RDscan2/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3809, in get_loc (rule bwa_mem, line 2, /mnt/f/RD/RDscan-1.0.4/workflow/rules/mapping.smk)
MissingInputException: Missing input files for rule bwa_mem:
    output: results/mapped/28.bam, results/mapped/28.bam.bai
    wildcards: sample=28
    affected files:
        /test/reads/28_1.fastq.gz
        /test/reads/28_2.fastq.gz

**Comment by dbespiatykh** [comment]
The error indicates that the files are not accessible at the specified file path, try using the absolute path (in terminal go to the location of 28_*.fastq.gz, type `pwd` and use that path). Also try `ls /test/reads/` does it print 28_1.fastq.gz and 28_2.fastq.gz?

**Comment by thomasprasad** [comment]
Resolved, 
As suggested was not having access to files with faulty path

Thanking again for prompt respone and help
